// generated by /crisp/gpu_side/.code_generation/erode_dilate_matmxn.lua on 22.10.2021, 20:49:11

#version 330 core

in vec2 _tex_coord;
out vec4 _out;

uniform sampler2D _texture;
uniform vec2 _texture_size;
uniform mat2x4 _structuring_element;

float to_value(float v)
{
    // project:
    // -1 -> infinity
    //  0 -> infinity
    //  1 -> 1
    return float(uint(int(v -1.1))) + 1;
}
void main()
{
    vec2 step_size = 1.f / _texture_size;
    vec4 min_v = vec4(2);

    min_v = min(min_v,to_value(_structuring_element[0][0]) * texture(_texture, _tex_coord + (vec2(-1, -1) * step_size)));
    min_v = min(min_v,to_value(_structuring_element[0][1]) * texture(_texture, _tex_coord + (vec2(-1, 0) * step_size)));
    min_v = min(min_v,to_value(_structuring_element[0][2]) * texture(_texture, _tex_coord + (vec2(-1, 1) * step_size)));
    min_v = min(min_v,to_value(_structuring_element[0][3]) * texture(_texture, _tex_coord + (vec2(-1, 2) * step_size)));
    min_v = min(min_v,to_value(_structuring_element[1][0]) * texture(_texture, _tex_coord + (vec2(0, -1) * step_size)));
    min_v = min(min_v,to_value(_structuring_element[1][1]) * texture(_texture, _tex_coord + (vec2(0, 0) * step_size)));
    min_v = min(min_v,to_value(_structuring_element[1][2]) * texture(_texture, _tex_coord + (vec2(0, 1) * step_size)));
    min_v = min(min_v,to_value(_structuring_element[1][3]) * texture(_texture, _tex_coord + (vec2(0, 2) * step_size)));

    _out = min_v;
}